### ISSUE TITLE
Unable to receive Unity messages.

### ISSUE THREAD

**Issue by kgh4770** [learntoflutter/flutter_embed_unity#19] opened 2024-05-31 07:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unity version

- [X] I am using Unity 2022.3 LTS

### Common issues

- [X] I have checked the common issues

### Flutter version

3.22.1

### Description

Unity

SendToFlutter.Send("setLoadScene:" + sceneNm);

Flutter
 EmbedUnity(
                        onMessageFromUnity: (String message) {
                          print('unityMessage : ${message}');
                        }
                    )

Unable to receive Unity messages.

### Minimum reproducible example (MRE)

unity
============================

using UnityEngine;

public class FlutterConnection : MonoBehaviour {

    void Awake(){
        Debug.Log("FlutterConnection Awake");
        SendToFlutter.Send("FlutterConnectionInit");
    }

    public void setLoadScene(string sceneNm) {
        Debug.Log("main setLoadScene sceneNm = " + sceneNm);
        SceneMangerControl.LoadScene(sceneNm);
        SendToFlutter.Send("setLoadScene:" + sceneNm);
    }
}

============================
flutter 

import 'package:flutter_embed_unity/flutter_embed_unity.dart';

 EmbedUnity(
                        onMessageFromUnity: (String message) {
                          print('unity Msg : ${message}');
                        }
                    ),

### What platforms are you seeing the problem on?

Android

### Devices

android 14 

### Anything else?

doesn't exist

**Comment by jamesncl** [comment] 2024-05-31 07:38
Thanks for the bug report. However, I am unable to reproduce your issue using the example project. I added this to [SendToFlutterSceneLoaded.cs](https://github.com/learntoflutter/flutter_embed_unity/blob/main/example_unity_2022_3_project/Assets/Example/Scripts/SendToFlutterSceneLoaded.cs):

```csharp
    void Awake(){
        Debug.Log("FlutterConnection Awake");
        SendToFlutter.Send("FlutterConnectionInit");
    }
```

Then exported the Unity project to the example android project [flutter_embed_unity_2022_3_android/example](https://github.com/learntoflutter/flutter_embed_unity/tree/main/flutter_embed_unity_2022_3_android/example), ran it, and received this in console:

> I/flutter (19710): Received from Unity FlutterConnectionInit
> I/flutter (19710): Received from Unity scene_loaded

So, I think there must be something wrong with how you have setup your project. Some ideas to investigate:

- Is your `FlutterConnection.cs` script attached to an active game object in your scene?
- Is your scene the 'main' scene, i.e. is it the one which is loaded when Unity starts up?

**Comment by jamesncl** [comment] 2024-05-31 07:52
Maybe check [SendToFlutter.java](https://github.com/learntoflutter/flutter_embed_unity/blob/main/flutter_embed_unity_2022_3_android/android/src/main/kotlin/com/learntoflutter/flutter_embed_unity_android/messaging/SendToFlutter.java) - if somehow this class method name is changed / obfuscated during your build, message passing will break. However the @Keep annotation should prevent this

**Comment by kgh4770** [comment] 2024-05-31 12:09
===Unity =====

I/Unity   (29383): FlutterConnection Awake
I/Unity   (29383): FlutterConnection:Awake()
I/Unity   (29383): SendToFlutter:Send(String)

==== Flutter ====
SendToFlutter.java 

I/System.out(29383): unityMsg :FlutterConnectionInit    <<=== A message arrives

=================================================


SendToFlutter.java

if(methodChannel != null) {
    System.out.println("unityMsg :"+data);
    methodChannel.invokeMethod(methodNameSendToFlutter, data);
}



====================================


If you look here, the message is delivered normally up to this point.



It doesn't seem to have progressed since then.

Is there anything else I should check?

**Comment by kgh4770** [comment] 2024-05-31 12:12
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version 10.0.22631.3593], locale ko-KR)
    • Flutter version 3.22.1 on channel stable at C:\AndroidStudio\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision a14f74ff3a (9 days ago), 2024-05-22 11:08:21 -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or higher)

[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\admin\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio1\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.10.1)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.10.34928.147
    • Windows 10 SDK version 10.0.22621.0

[√] Android Studio (version 2023.3)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.10+0--11572160)

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22631.3593]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 125.0.6422.113
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 125.0.2535.79

[√] Network resources
    • All expected network resources are available.

**Comment by kgh4770** [comment] 2024-05-31 12:16
flutter_unity_widget

I used it.

but 

flutter_embed_unity

There is no need to add Unity sources to Flutter. 

I am very excited about the project.

Thanks for your help.

:)

**Comment by kgh4770** [comment] 2024-06-01 08:19
unity_message_listeners.dart line 27 

iOS connects normally. But it doesn't work on android

Android System.out.print 
=> unityMsg data : FlutterConnectionInit / methodNameSendToFlutter : sendToFlutter / methodChannel : io.flutter.plugin.common.MethodChannel@1c6029c

Is it correct for the methodChannel to work like this?

**Comment by jamesncl** [comment] 2024-06-03 10:40
You should debug and step through `unity_message_listeners.dart` and see what happens. For example see my comments below:

```dart

  Future<dynamic> _methodCallHandler(MethodCall call) async {
    // 1. Does it reach here? What is the content of call.method and call.arguments?
    if (call.method == FlutterEmbedConstants.methodNameSendToFlutter) {
      // 2. Does it reach here?
      final data = call.arguments.toString();
      switch (EmbedUnityPreferences.messageFromUnityListeningBehaviour) {
        // 3. Does it reach here?
        case MessageFromUnityListeningBehaviour.allWidgetsReceiveMessages:
          {
            // 4. There should be at least 1 listener here - what is the value of _listeners.length?
            for (var listener in _listeners) {
              listener.onMessageFromUnity(data);
            }
          }
        case MessageFromUnityListeningBehaviour.onlyMostRecentlyCreatedWidgetReceivesMessages:
          {
            if (_listeners.isNotEmpty) {
              _listeners.last.onMessageFromUnity(data);
            }
          }
      }
    }
  }
```

**Comment by Azis202017** [comment] 2024-06-07 23:29
Hello same here, i dont get the data from message

**Comment by jamesncl** [comment] 2024-06-10 13:03
@kgh4770 @Azis202017 Can you please confirm what version of Flutter you had installed when you created your Flutter project?

**Comment by jamesncl** [comment] 2024-06-10 13:55
I have created a new Flutter project (using flutter 3.22), and followed all the [steps in the README](https://pub.dev/packages/flutter_embed_unity) using the [example Unity project](https://github.com/learntoflutter/flutter_embed_unity/tree/main/example_unity_2022_3_project), and messaging appears to work for me. This means there must be something about how you are setting up your project which is causing the issue.

So I will need more information in order to help you. You either need to:
1. Create a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the problem
2. Follow the debugging steps in [my previous comment](https://github.com/learntoflutter/flutter_embed_unity/issues/19#issuecomment-2144868435) and let me know the results

**Comment by jamesncl** [comment] 2024-09-10 12:14
As per my last comment, I'm unable to help further without more information, so I'll close this issue for now. If you are able to share a reproducible example I will reopen the issue.

**Closed by jamesncl** 2024-09-10 12:14 UTC
Labels: bug, awaiting feedback
