### ISSUE TITLE
Intermittent Character Missing in Text when Implementing Unity in Flutter

### ISSUE THREAD

**Issue by GreejeshGajera** [learntoflutter/flutter_embed_unity#25] opened 2024-07-09 15:43 UTC
### Description

We are experiencing an intermittent issue where characters in specific words are missing when integrating Unity into a Flutter application. This issue has been observed sporadically and affects the text display within the app. The problem is illustrated in the attached image, where certain letters in words are not rendered correctly, resulting in incomplete words.

**Steps to Reproduce:**

	1.	Open the Flutter app that integrates Unity.
	2.	Navigate to the section where the Unity component is displayed.
	3.	Observe the text within the Unity component.
	4.	Note that some words have missing characters as shown in the attached screenshot.

**Expected Behavior:**

All text characters should render correctly and completely without any missing letters.

**Actual Behavior:**

Intermittently, characters in certain words are missing, leading to incomplete words being displayed.

**Screenshot:**

![Issue_Image](https://github.com/learntoflutter/flutter_embed_unity/assets/63508623/f240a8fd-2f28-4006-97d5-d432231e305b)

**Environment:**

	•	Flutter Version: 3.22.1
	•	Unity Version:  2022.3.28f1
	•	flutter_embed_unity: ^1.0.4
	•	Device/OS: Android/Ios
	•	Other Relevant Information: (Any other relevant details that might help in diagnosing the issue)

**Additional Context:**

	•	The issue does not occur consistently and appears to be random.
	•	We have verified that the text data being passed to Unity is complete and correct.
	•	The issue is only observed after integrating Unity within the Flutter app.

**Possible Cause:**

We suspect that this might be an issue related to the rendering engine or a potential conflict between Flutter and Unity text rendering mechanisms.

**Steps Taken to Troubleshoot:**

	•	Verified the completeness of text data before passing it to Unity.
	•	Checked for any known issues or updates related to text rendering in both Flutter and Unity.

**Request:**

We would appreciate any insights or suggestions on how to resolve this issue. If there are any specific tests or debug logs needed, please let us know, and we will provide them promptly.

Feel free to customize the template further based on the specifics of your environment and any additional information you might have.

**Comment by jamesncl** [comment] 2024-07-09 16:13
Thanks for the bug report, this does seem very strange. Not sure why this would happen - I'm also passing text to Unity to display in TextMeshPro but I haven't encountered this issue. Some questions:

- Could you share how you are sending your messages to Unity - eg are you using `jsonEncode` to encode a `Map<String, dynamic>`?
- How are you decoding the message on the Unity side?
- Are you using TextMeshPro? Are you sure all the SDF files are being included in the build (they need to be in a Resources folder)
- The screenshots from Unity - are these taken from the Unity Editor or from a real device (using Build And Run)?

**Comment by jamesncl** [comment] 2024-07-09 16:14
Also, what language / region do you have set on the device?

**Comment by GreejeshGajera** [comment] 2024-07-09 17:02
- I am not passing any messages from the Flutter side; this message is shown from the Unity side.

- No, we are not using TextMeshPro. We are only using Unity UI Text.

- I have checked on both Unity Editor and a real device.

**Comment by jamesncl** [comment] 2024-07-09 17:48
That's really strange. I'm not sure what could cause that. Have you tried the [flutter_unity_widget](https://pub.dev/packages/flutter_unity_widget) package? I would be interested to see if the same problem happens with that package. It might help to narrow down where the problem is

**Comment by jamesncl** [comment] 2024-09-10 12:12
As I'm unable to help further, so I'll close this issue. If you have any further information or a reproducible example you can share, feel free to comment further and I'll reopen.

**Closed by jamesncl** 2024-09-10 12:12 UTC
Labels: bug
