### ISSUE TITLE
 flutter_embed_unity plugin  with google_maps_flutter cause crashing my app

### ISSUE THREAD

**Issue by abdelrahman-abied** [learntoflutter/flutter_embed_unity#28] opened 2024-08-15 06:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Unity version

- [X] I am using Unity 2022.3 LTS

### Common issues

- [X] I have checked the common issues

### Flutter version

3.22.2 environment:   sdk: ">=3.2.0 <4.0.0" 

### Description

 flutter_embed_unity plugin  with google_maps_flutter cause crashing my app on IOS 

### What platforms are you seeing the problem on?

iOS

### Devices

any ios devices

**Comment by timbotimbo** [comment] 2024-08-15 21:30
Can you add more information?

- Can you find an error or exception in the logs?
- How do you combine both widgets?
  For example: 
  - both widgets in a scrollview
  -  on top of each other in a stack, 
  - on different tabs in a tabbar, 
  - on separate pages that get pushed on top of each other,
- Does it crash instantly or on a specific action in your app?
- Can you show some sample code that reproduces this?

**Comment by abdelrahman-abied** [comment] 2024-08-16 11:24
Can you add more information? just add two dependencies in yaml 

Can you find an error or exception in the logs? no because app crash without any error in console just run app with xcode and check it
How do you combine both widgets? 
For example:
both widgets in a scrollview no 
on top of each other in a stack, no there is no stack or scroll widget
on different tabs in a tabbar, no
on separate pages that get pushed on top of each other, yes but i didn't add map widget just add google_maps_flutter in yaml
Does it crash instantly or on a specific action in your app? crashed instantly after opened the app
Can you show some sample code that reproduces this?

**Comment by jamesncl** [comment] 2024-08-19 11:11
I'm able to reproduce this by adding `google_maps_flutter: ^2.9.0` to the example project and attempting to run on an iPhone.

The app appears to crash on startup. The crash occurs in `libdispatch.dylib`:

> libdispatch.dylib`:
>     0x10511cd2c <+0>:  stp    x20, x21, [sp, #-0x10]!
>     0x10511cd30 <+4>:  adrp   x20, 7
>     0x10511cd34 <+8>:  add    x20, x20, #0xaf8          ; "BUG IN CLIENT OF LIBDISPATCH: trying to lock recursively"
>     0x10511cd38 <+12>: adrp   x21, 41
>     0x10511cd3c <+16>: add    x21, x21, #0x220          ; gCRAnnotations
>     0x10511cd40 <+20>: str    x20, [x21, #0x8]
>     0x10511cd44 <+24>: ldp    x20, x21, [sp], #0x10
> ->  0x10511cd48 <+28>: brk    #0x1                  <-- Break occurs here

And here's the stacktrace from Xcode:

> 0	0x000000010511cd48 in _dispatch_once_wait.cold.1 ()
> 1	0x00000001050e32b0 in _dispatch_once_wait ()
> 2	0x0000000104b9ac1c in findPrimitiveInfoNoAssert ()
> 3	0x0000000104b96f74 in interposed_dispatch_semaphore_create ()
> 4	0x000000010a9560f4 in UnityClassic::Baselib_SystemSemaphore_CreateInplace(void*) ()
> 5	0x000000010a27fa5c in MemoryManager::InitializeMemory() ()
> 6	0x00000001b1657864 in std::__1::__call_once(unsigned long volatile&, void*, void (*)(void*)) ()
> 7	0x000000010a27f954 in MemoryManager::InitializeMemoryLazily() ()
> 8	0x000000010a27ef44 in operator new(unsigned long) ()
> 9	0x0000000104b9aa1c in invocation function for block in initializePrimitiveMap() ()
> 10	0x00000001050e27bc in _dispatch_client_callout ()
> 11	0x00000001050e434c in _dispatch_once_callout ()
> 12	0x0000000104b9ac1c in findPrimitiveInfoNoAssert ()
> 13	0x0000000104b96f74 in interposed_dispatch_semaphore_create ()
> 14	0x0000000105474cb0 in GTMTLCaptureManager_init ()
> 15	0x00000001053da5d0 in __CaptureInterposerInit_block_invoke ()
> 16	0x00000001050e27bc in _dispatch_client_callout ()
> 17	0x00000001050e434c in _dispatch_once_callout ()
> 18	0x00000001c4a16a70 in invocation function for block in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const::$_0::operator()() const ()
> 19	0x00000001c4a01ba8 in invocation function for block in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const ()
> 20	0x00000001c4a00c9c in invocation function for block in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const ()
> 21	0x00000001c49ffe5c in dyld3::MachOFile::forEachLoadCommand(Diagnostics&, void (load_command const*, bool&) block_pointer) const ()
> 22	0x00000001c4a18314 in dyld3::MachOFile::forEachSection(void (dyld3::MachOFile::SectionInfo const&, bool, bool&) block_pointer) const ()
> 23	0x00000001c4a0b4ac in dyld3::MachOAnalyzer::forEachInitializer(Diagnostics&, dyld3::MachOAnalyzer::VMAddrConverter const&, void (unsigned int) block_pointer, void const*) const ()
> 24	0x00000001c4a0ae18 in dyld4::Loader::findAndRunAllInitializers(dyld4::RuntimeState&) const ()
> 25	0x00000001c4a0cc44 in dyld4::JustInTimeLoader::runInitializers(dyld4::RuntimeState&) const ()
> 26	0x00000001c4a0a384 in dyld4::Loader::runInitializersBottomUp(dyld4::RuntimeState&, dyld3::Array<dyld4::Loader const*>&) const ()
> 27	0x00000001c4a11038 in dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const::$_1::operator()() const ()
> 28	0x00000001c4a10d6c in dyld4::Loader::runInitializersBottomUpPlusUpwardLinks(dyld4::RuntimeState&) const ()
> 29	0x00000001c49ff304 in dyld4::APIs::runAllInitializersForMain() ()
> 30	0x00000001c4a163b0 in dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) ()
> 31	0x00000001c4a3aef4 in start ()

It's quite an unhelpful low-level stacktrace and appears to be part of the app initialization process. Searching for "BUG IN CLIENT OF LIBDISPATCH: trying to lock recursively" on stackoverflow does not yield much.

The stacktrace contains ` in UnityClassic::Baselib_SystemSemaphore_CreateInplace(void*)` which seems to indicate the problem is in Unity rather than Google Maps. Unfortunately I have no idea how to view whatever `UnityClassic::Baselib` is or debug further. It may be worth raising this in the [Unity issue tracker](https://issuetracker.unity3d.com/). It may also be worth trying [flutter_unity_widget](https://pub.dev/packages/flutter_unity_widget), which supports different versions of Unity which may not have this issue

**Comment by jamesncl** [comment] 2024-08-19 11:26
I found the same `UnityClassic::Baselib_SystemSemaphore_CreateInplace` line in [this Unity forum discussion: Unity 2021.3.6f1, Xcode 14, iOS 16 Problem: UnityFramework crash before main()](https://discussions.unity.com/t/unity-2021-3-6f1-xcode-14-ios-16-problem-unityframework-crash-before-main/894790)

As stated in that thread, disabling thread performance checking appears to resolve the error above (but then we get a new error, see below)

![b7cc87349704f02ed91be4b0014a353a2e005d98_2_690x228](https://github.com/user-attachments/assets/222a59a9-8b0b-455c-98d8-ed4786f19c4a)

The app then crashes at a later stage, it appears to be when Unity attempts to send the scene loaded message:

> Thread 1 Queue : com.apple.main-thread (serial)
> 0	0x00000001c4a706f8 in __abort_with_payload ()
> 1	0x00000001c4a7be34 in abort_with_payload_wrapper_internal ()
> 2	0x00000001c4a7be68 in abort_with_payload ()
> 3	0x00000001c4a08dd4 in dyld4::halt(char const*, dyld4::StructuredError const*) ()
> 4	0x00000001c4a59994 in dyld4::APIs::_dyld_missing_symbol_abort() ()
> 5	0x000000010a88ca5c in SendToFlutter_FlutterEmbedUnityIosSendToFlutter_mAA673B375B4CBFFEE14A3569ED35D238DB827998 ()
> 6	0x000000010a88c6c0 in SendToFlutter_Send_mC3EEBDA79530F83C75829EFC506B20AF3C9B16AE ()
> 7	0x000000010a88c48c in SendToFlutterSceneLoaded_OnSceneLoaded_mFF979CE9081FCD0E3A85395F2B37B5938CDF1760 ()
> 8	0x000000010a6744f4 in RuntimeInvoker_TrueVoid_t4861ACF8F4594C3437BB48B6E56783494B843915_Scene_tA1DC762B79745EB5140F054C884855B922318356_Int32_t680FF22E76F6EFAD4375103CBBFFA0421349384C(void (*)(), MethodInfo const*, void*, void**, void*) ()
> 9	0x000000010a61bba4 in InvokerActionInvoker2<void*, void*>::Invoke(void (*)(), MethodInfo const*, void*, void*, void*) ()
> 10	0x000000010a64523c in UnityAction_2_Invoke_m05FE3765125338EF158A176DD190F4CA6DB6F520_ClosedInstInvoker(UnityAction_2_t742C43FA6EAABE0458C753DFE15FDDFAE01EA73F*, void*, void*, MethodInfo const*) ()
> 11	0x000000010b16cdb0 in UnityAction_2_Invoke_m05FE3765125338EF158A176DD190F4CA6DB6F520_gshared_inline(UnityAction_2_t742C43FA6EAABE0458C753DFE15FDDFAE01EA73F*, void*, void*, MethodInfo const*) ()
> 12	0x000000010a789000 in UnityAction_2_Invoke_mA8E9470BBBEC323CF7103F7A75CD6E8911B2DB6A_inline(UnityAction_2_t1C08AEB5AA4F72FEFAB7F303E33C8CFFF80A8C3A*, Scene_tA1DC762B79745EB5140F054C884855B922318356, int, MethodInfo const*) ()
> 13	0x000000010b156664 in SceneManager_Internal_SceneLoaded_m929615D240C989E0EA73E3141C8AAAA73BCB51D4 ()
> 14	0x000000010a6b8230 in RuntimeInvoker_FalseVoid_t4861ACF8F4594C3437BB48B6E56783494B843915_Scene_tA1DC762B79745EB5140F054C884855B922318356_Int32_t680FF22E76F6EFAD4375103CBBFFA0421349384C(void (*)(), MethodInfo const*, void*, void**, void*) ()
> 15	0x000000010a86d1f8 in il2cpp::vm::Runtime::InvokeWithThrow(MethodInfo const*, void*, void**) ()
> 16	0x000000010a86d140 in il2cpp::vm::Runtime::Invoke(MethodInfo const*, void*, void**, Il2CppException**) ()
> 17	0x0000000109d69450 in scripting_method_invoke(ScriptingMethodPtr, ScriptingObjectPtr, ScriptingArguments&, ScriptingExceptionPtr*, bool) ()
> 18	0x0000000109d763c0 in ScriptingInvocation::Invoke(ScriptingExceptionPtr*, bool) ()
> 19	0x0000000109cab42c in RuntimeSceneManager::EndIntegrateMainThread(UnityScene*, SceneLoadingMode) ()
> 20	0x0000000109c9f804 in LoadSceneOperation::IntegrateMainThread() ()
> 21	0x0000000109ca05ec in PreloadManager::UpdatePreloadingSingleStep(PreloadManager::UpdatePreloadingFlags, int) ()
> 22	0x0000000109ca10a8 in PreloadManager::UpdatePreloading() ()
> 23	0x000000010a1d6ed4 in UnityPlayerLoopImpl(bool) ()
> 24	0x0000000109b4b260 in UnityRepaint ()
> 25	0x0000000109b4b220 in -[UnityAppController(Rendering) repaint] ()
> 26	0x0000000109b4b1a4 in -[UnityAppController(Rendering) repaintDisplayLink] ()
> 27	0x00000001a2954dc4 in CA::Display::DisplayLinkItem::dispatch_(CA::SignPost::Interval<(CA::SignPost::CAEventCode)835322056>&) ()
> 28	0x00000001a29530e8 in CA::Display::DisplayLink::dispatch_items(unsigned long long, unsigned long long, unsigned long long) ()
> 29	0x00000001a2953a70 in display_timer_callback(__CFMachPort*, void*, long, void*) ()
> 30	0x00000001a1265d68 in __CFMachPortPerform ()
> 31	0x00000001a1265ca4 in __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ ()
> 32	0x00000001a1265bc4 in __CFRunLoopDoSource1 ()
> 33	0x00000001a1264a0c in __CFRunLoopRun ()
> 34	0x00000001a1263cd8 in CFRunLoopRunSpecific ()
> 35	0x00000001e5cb11a8 in GSEventRunModal ()
> 36	0x00000001a389dae8 in -[UIApplication _run] ()
> 37	0x00000001a3951d98 in UIApplicationMain ()
> 38	0x0000000102c68640 in main at /Users/james/GithubRepos/flutter_embed_unity/flutter_embed_unity/example/ios/Runner/AppDelegate.swift:6
> 39	0x00000001c4a3b154 in start ()

**Comment by jamesncl** [comment] 2024-08-19 11:54
This does appear to solve the issue, I'm able to run Google Maps with Unity on iOS after disabling 'Thread performance checker'. No idea what that does or why it solves the problem, but I think this is the best I can do to help. I'll add this to the list of common issues in the README. Let me know if this doesn't work.

![Screenshot 2024-08-19 at 12 50 14](https://github.com/user-attachments/assets/d63b207b-011c-4608-a412-133b202dd485)

**Comment by timbotimbo** [comment] 2024-08-19 12:12
In the past with flutter_unity_widget that optikb caused crashs with xcode 14, but I believe that was fixed in a later version. It could be that a new release triggers it again.

So this might be related to the xcode verison used.

**Closed** 2024-08-25 09:39 UTC
Labels: bug
