### ISSUE TITLE
iOS can't run

### ISSUE THREAD

**Issue by nguyenquynh201** [learntoflutter/flutter_embed_unity#11] opened 2023-11-20 14:29 UTC
`Setting UIViewControllerBasedStatusBarAppearance to NO is no longer supported.
Apple actively discourages that, and all application-wide methods of changing status bar appearance are deprecated`
Flutter doctor - ok
Android build and run - ok
Unity-IPhone/Data target - ok
Runner lib added from Unity-IPhone - ok
Other points from README - ok

Device IOS - 16.6.1
Target SDK (Unity/Xcode) - 12.0

**Comment by jamesncl** [comment] 2023-11-20 16:34
Thanks for the bug report. I also get `UIViewControllerBasedStatusBarAppearance to NO is no longer supported` but my app still runs - this isn't an error, it is just a warning.

So, I think the actual issue you are having is something else - please have another look at you console output or post it here in full, I suspect there is another error message you have missed?

**Comment by nguyenquynh201** [comment] 2023-11-21 03:24
<img width="1397" alt="image" src="https://github.com/learntoflutter/flutter_embed_unity/assets/80728170/1c1c9da1-807a-4269-ba77-f6c17729e232">
I set it up from another project and it ran successfully, but when I applied it to my main project it crashed, you can see in the picture.

**Comment by jamesncl** [comment] 2023-11-21 14:04
I think you'll need to do a bit more investigating to narrow down the cause of your error. I can't tell from that picture what the issue is. What I suggest is:

- Try to create a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example): a set of steps that other people can follow to reliably reproduce the same error
- Use the Xcode debugger to pinpoint the exact part of your program which throws the error - from the picture above it looks like it happens when you try to send a message from Unity to Flutter when the scene loads. Try commenting out calls to SendToFlutter on scene load and see if that changes anything.

**Comment by jamesncl** [comment] 2023-11-22 10:43
Without more information or specific steps which will reproduce an error I will reluctantly have to close this issue for now, as this doesn't appear to be a verifiable bug in flutter_embed_unity. If you are able to produce more information please feel free to comment further.

**Closed by jamesncl** 2023-11-22 10:43 UTC
Labels: awaiting feedback

**Comment by jamesncl** [comment] 2023-11-22 16:34
This may be related to the other issue you raised #8 - if you explain in #8 **in detail** what you did to resolve FBLPromises not found, I may be able to help further
